version: "2.1"

services:
  db:
    image: "mysql:5.7"
    ports:
      - 3306:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD="yes"
      - MYSQL_USER=hyperfoca
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=hyperfoca
    networks:
      - hyperfoca-stack
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  db:

networks: {hyperfoca-stack: {}}
